/*
 * SettingsWindowView.java
 *
 * Created on 2010-03-18, 01:20:03
 */
package com.panozona.converter;

import com.panozona.converter.settings.AggregatedSettings;
import com.panozona.converter.utils.FileFilterDir;
import com.panozona.converter.utils.InfoException;
import com.panozona.converter.utils.FileFilterJar;
import com.panozona.converter.utils.Info;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Marek Standio
 */
public class SettingsWindowView extends javax.swing.JFrame {

    private String initialmemoryLimitValue = "-1";

    /** Creates new form SettingsWindowView */
    public SettingsWindowView() {
        initComponents();
        setTitle("SaladoConverter settings");
        setIconImage(Toolkit.getDefaultToolkit().getImage(MainWindowView.class.getResource("resources/icons/appicon.png")));
        allowCloseFlag = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        TabbedPane = new javax.swing.JTabbedPane();
        GeneralTab = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonGERestoreDefault = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxGESearchSub = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldGESearchDepth = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldGEDirectory = new javax.swing.JTextField();
        jButtonGEBrowseDirectory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMemoryLimit = new javax.swing.JTextField();
        DeepZoomTilerTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldECQuality = new javax.swing.JTextField();
        jTextFieldECOverlap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldECDirectory = new javax.swing.JTextField();
        jButtonECBrowseDirectory = new javax.swing.JButton();
        jComboBoxECInterpolation = new javax.swing.JComboBox();
        jButtonECRestoreDefault = new javax.swing.JButton();
        EquirectangularToCubicTab = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDZTQuality = new javax.swing.JTextField();
        jTextFieldDZTOverlap = new javax.swing.JTextField();
        jTextFieldDZTTileSize = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDZTDirectory = new javax.swing.JTextField();
        jButtonDZTBrowseDirectory = new javax.swing.JButton();
        jButtonDZTRestoreDefault = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.setName("jFileChooser"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        TabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.panozona.converter.SaladoConverter.class).getContext().getResourceMap(SettingsWindowView.class);
        TabbedPane.setToolTipText(resourceMap.getString("TabbedPane.toolTipText")); // NOI18N
        TabbedPane.setName("TabbedPane"); // NOI18N

        GeneralTab.setName("GeneralTab"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jButtonGERestoreDefault.setText(resourceMap.getString("jButtonGERestoreDefault.text")); // NOI18N
        jButtonGERestoreDefault.setActionCommand(resourceMap.getString("jButtonGERestoreDefault.actionCommand")); // NOI18N
        jButtonGERestoreDefault.setName("jButtonGERestoreDefault"); // NOI18N
        jButtonGERestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGERestoreDefaultActionPerformed(evt);
            }
        });

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jComboBoxGESearchSub.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "false", "true" }));
        jComboBoxGESearchSub.setName("jComboBoxGESearchSub"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jTextFieldGESearchDepth.setName("jTextFieldGESearchDepth"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jTextFieldGEDirectory.setName("jTextFieldGEDirectory"); // NOI18N

        jButtonGEBrowseDirectory.setText(resourceMap.getString("jButtonGEBrowseDirectory.text")); // NOI18N
        jButtonGEBrowseDirectory.setName("jButtonGEBrowseDirectory"); // NOI18N
        jButtonGEBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGEBrowseDirectoryActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextFieldMemoryLimit.setText(resourceMap.getString("jTextFieldMemoryLimit.text")); // NOI18N
        jTextFieldMemoryLimit.setName("jTextFieldMemoryLimit"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGERestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMemoryLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldGEDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGEBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldGESearchDepth, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxGESearchSub, 0, 225, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxGESearchSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldGESearchDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldGEDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGEBrowseDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMemoryLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButtonGERestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout GeneralTabLayout = new javax.swing.GroupLayout(GeneralTab);
        GeneralTab.setLayout(GeneralTabLayout);
        GeneralTabLayout.setHorizontalGroup(
            GeneralTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GeneralTabLayout.setVerticalGroup(
            GeneralTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("GeneralTab.TabConstraints.tabTitle"), GeneralTab); // NOI18N

        DeepZoomTilerTab.setName("DeepZoomTilerTab"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldECQuality.setText(resourceMap.getString("jTextFieldECQuality.text")); // NOI18N
        jTextFieldECQuality.setName("jTextFieldECQuality"); // NOI18N

        jTextFieldECOverlap.setText(resourceMap.getString("jTextFieldECOverlap.text")); // NOI18N
        jTextFieldECOverlap.setName("jTextFieldECOverlap"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jTextFieldECDirectory.setText(resourceMap.getString("jTextFieldECDirectory.text")); // NOI18N
        jTextFieldECDirectory.setName("jTextFieldECDirectory"); // NOI18N

        jButtonECBrowseDirectory.setText(resourceMap.getString("jButtonECBrowseDirectory.text")); // NOI18N
        jButtonECBrowseDirectory.setName("jButtonECBrowseDirectory"); // NOI18N
        jButtonECBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonECBrowseDirectoryActionPerformed(evt);
            }
        });

        jComboBoxECInterpolation.setName("jComboBoxECInterpolation"); // NOI18N

        jButtonECRestoreDefault.setText(resourceMap.getString("jButtonECRestoreDefault.text")); // NOI18N
        jButtonECRestoreDefault.setName("jButtonECRestoreDefault"); // NOI18N
        jButtonECRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonECRestoreDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(jTextFieldECQuality, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxECInterpolation, 0, 259, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldECDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonECBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldECOverlap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addComponent(jButtonECRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldECQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldECOverlap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxECInterpolation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldECDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonECBrowseDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButtonECRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout DeepZoomTilerTabLayout = new javax.swing.GroupLayout(DeepZoomTilerTab);
        DeepZoomTilerTab.setLayout(DeepZoomTilerTabLayout);
        DeepZoomTilerTabLayout.setHorizontalGroup(
            DeepZoomTilerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeepZoomTilerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DeepZoomTilerTabLayout.setVerticalGroup(
            DeepZoomTilerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeepZoomTilerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("DeepZoomTilerTab.TabConstraints.tabTitle"), DeepZoomTilerTab); // NOI18N

        EquirectangularToCubicTab.setName("EquirectangularToCubicTab"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jTextFieldDZTQuality.setName("jTextFieldDZTQuality"); // NOI18N

        jTextFieldDZTOverlap.setName("jTextFieldDZTOverlap"); // NOI18N

        jTextFieldDZTTileSize.setName("jTextFieldDZTTileSize"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jTextFieldDZTDirectory.setText(resourceMap.getString("jTextFieldDZTDirectory.text")); // NOI18N
        jTextFieldDZTDirectory.setName("jTextFieldDZTDirectory"); // NOI18N

        jButtonDZTBrowseDirectory.setText(resourceMap.getString("jButtonDZTBrowseDirectory.text")); // NOI18N
        jButtonDZTBrowseDirectory.setName("jButtonDZTBrowseDirectory"); // NOI18N
        jButtonDZTBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDZTBrowseDirectoryActionPerformed(evt);
            }
        });

        jButtonDZTRestoreDefault.setText(resourceMap.getString("jButtonDZTRestoreDefault.text")); // NOI18N
        jButtonDZTRestoreDefault.setName("jButtonDZTRestoreDefault"); // NOI18N
        jButtonDZTRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDZTRestoreDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(45, 45, 45)
                        .addComponent(jTextFieldDZTQuality, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                    .addComponent(jButtonDZTRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldDZTDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDZTBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldDZTOverlap, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jTextFieldDZTTileSize, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDZTQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDZTOverlap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDZTTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldDZTDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDZTBrowseDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButtonDZTRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout EquirectangularToCubicTabLayout = new javax.swing.GroupLayout(EquirectangularToCubicTab);
        EquirectangularToCubicTab.setLayout(EquirectangularToCubicTabLayout);
        EquirectangularToCubicTabLayout.setHorizontalGroup(
            EquirectangularToCubicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquirectangularToCubicTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EquirectangularToCubicTabLayout.setVerticalGroup(
            EquirectangularToCubicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquirectangularToCubicTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("EquirectangularToCubicTab.TabConstraints.tabTitle"), EquirectangularToCubicTab); // NOI18N

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOK.setText(resourceMap.getString("jButtonOK.text")); // NOI18N
        jButtonOK.setName("jButtonOK"); // NOI18N
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TabbedPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        collectAllData();
        if (allowCloseFlag) {
            if (!initialmemoryLimitValue.equals(jTextFieldMemoryLimit.getText())){
                JOptionPane.showMessageDialog(this, Info.GE_MEM_LIMIT_WARNING);
            }
            this.dispose();
        }
        allowCloseFlag = true;
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonGERestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGERestoreDefaultActionPerformed
        jComboBoxGESearchSub.setSelectedItem(aggstngs.ge.getDefaultSearchSubDirs());
        jTextFieldGESearchDepth.setText(aggstngs.ge.getDefaultSearchDepth());
        jTextFieldGEDirectory.setText(aggstngs.ge.getDefaultTmpDir());
        jTextFieldMemoryLimit.setText(aggstngs.ge.getDefaultMemoryLimit());
    }//GEN-LAST:event_jButtonGERestoreDefaultActionPerformed

    private void jButtonECRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonECRestoreDefaultActionPerformed
        jTextFieldECOverlap.setText(aggstngs.ec.getDefaultOverlap());
        jComboBoxECInterpolation.setSelectedItem(aggstngs.ec.getDefaultInterpolation());
        jTextFieldECQuality.setText(aggstngs.ec.getDefaultQuality());
        jTextFieldECDirectory.setText(aggstngs.ec.getDefaultJarDir());
    }//GEN-LAST:event_jButtonECRestoreDefaultActionPerformed

    private void jButtonDZTRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDZTRestoreDefaultActionPerformed
        jTextFieldDZTOverlap.setText(aggstngs.dzt.getDefaultOverlap());
        jTextFieldDZTTileSize.setText(aggstngs.dzt.getDefaultTileSize());
        jTextFieldDZTQuality.setText(aggstngs.dzt.getDefaultQuality());
        jTextFieldDZTDirectory.setText(aggstngs.dzt.getDefaultJarDir());
    }//GEN-LAST:event_jButtonDZTRestoreDefaultActionPerformed

    private void jButtonECBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonECBrowseDirectoryActionPerformed
        jFileChooser.resetChoosableFileFilters();
        jFileChooser.setFileFilter(new FileFilterJar());
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser.setDialogTitle("Browse for EquirectangularToCubic.jar");
        jFileChooser.setCurrentDirectory(new File(aggstngs.ec.getJarDir()));
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                aggstngs.ec.setJarDir(jFileChooser.getSelectedFile().getAbsolutePath());
                jTextFieldECDirectory.setText(aggstngs.ec.getJarDir());
            } catch (InfoException ex) {
                showOptionPane(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonECBrowseDirectoryActionPerformed

    private void jButtonDZTBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDZTBrowseDirectoryActionPerformed
        jFileChooser.resetChoosableFileFilters();
        jFileChooser.setFileFilter(new FileFilterJar());
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser.setDialogTitle("Browse for EquirectangularToCubic.jar");
        jFileChooser.setCurrentDirectory(new File(aggstngs.dzt.getJarDir()));
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                aggstngs.dzt.setJarDir(jFileChooser.getSelectedFile().getAbsolutePath());
                jTextFieldDZTDirectory.setText(aggstngs.dzt.getJarDir());
            } catch (InfoException ex) {
                showOptionPane(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonDZTBrowseDirectoryActionPerformed

    private void jButtonGEBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGEBrowseDirectoryActionPerformed
        jFileChooser.resetChoosableFileFilters();
        jFileChooser.setFileFilter(new FileFilterDir());
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.setDialogTitle("Browse for tmp directory");
        jFileChooser.setCurrentDirectory(new File(aggstngs.ge.getTmpDir()));
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                aggstngs.ge.setTmpDir(jFileChooser.getSelectedFile().getAbsolutePath());
                jTextFieldGEDirectory.setText(aggstngs.ge.getTmpDir());
            } catch (InfoException ex) {
                showOptionPane(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonGEBrowseDirectoryActionPerformed

    public void displayAggregatedSettings(AggregatedSettings aggstngs) {
        this.aggstngs = aggstngs;

        jComboBoxECInterpolation.setModel(new DefaultComboBoxModel(this.aggstngs.ec.getInterpolationNames()));

        jComboBoxGESearchSub.setSelectedItem(aggstngs.ge.getSearchSubDirs());
        jTextFieldGESearchDepth.setText(aggstngs.ge.getSearchDepth());
        jTextFieldGEDirectory.setText(aggstngs.ge.getTmpDir());
        jTextFieldMemoryLimit.setText(aggstngs.ge.getMemoryLimit());
        initialmemoryLimitValue = aggstngs.ge.getMemoryLimit();

        jTextFieldDZTOverlap.setText(aggstngs.dzt.getOverlap());
        jTextFieldDZTTileSize.setText(aggstngs.dzt.getTileSize());
        jTextFieldDZTQuality.setText(aggstngs.dzt.getQuality());
        jTextFieldDZTDirectory.setText(aggstngs.dzt.getJarDir());

        jTextFieldECOverlap.setText(aggstngs.ec.getOverlap());
        jComboBoxECInterpolation.setSelectedItem(aggstngs.ec.getInterpolation());
        jTextFieldECQuality.setText(aggstngs.ec.getQuality());
        jTextFieldECDirectory.setText(aggstngs.ec.getJarDir());
    }

    private void collectAllData() {
        try {
            aggstngs.ge.setSearchSubDirs(jComboBoxGESearchSub.getSelectedItem().toString());
            aggstngs.ge.setSearchDepth(jTextFieldGESearchDepth.getText());
            aggstngs.ge.setTmpDir(jTextFieldGEDirectory.getText());
            aggstngs.ge.setMemoryLimit(jTextFieldMemoryLimit.getText());

            aggstngs.dzt.setOverlap(jTextFieldDZTOverlap.getText());
            aggstngs.dzt.setTileSize(jTextFieldDZTTileSize.getText());
            aggstngs.dzt.setQuality(jTextFieldDZTQuality.getText());
            aggstngs.dzt.setJarDir(jTextFieldDZTDirectory.getText());

            aggstngs.ec.setOverlap(jTextFieldECOverlap.getText());
            aggstngs.ec.setInterpolation(jComboBoxECInterpolation.getSelectedItem().toString());
            aggstngs.ec.setQuality(jTextFieldECQuality.getText());
            aggstngs.ec.setJarDir(jTextFieldECDirectory.getText());
        } catch (InfoException ex) {
            showOptionPane(ex.getMessage());
        }
    }

    private void showOptionPane(String message) {
        JOptionPane.showMessageDialog(this, message);
        allowCloseFlag = false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeepZoomTilerTab;
    private javax.swing.JPanel EquirectangularToCubicTab;
    private javax.swing.JPanel GeneralTab;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDZTBrowseDirectory;
    private javax.swing.JButton jButtonDZTRestoreDefault;
    private javax.swing.JButton jButtonECBrowseDirectory;
    private javax.swing.JButton jButtonECRestoreDefault;
    private javax.swing.JButton jButtonGEBrowseDirectory;
    private javax.swing.JButton jButtonGERestoreDefault;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxECInterpolation;
    private javax.swing.JComboBox jComboBoxGESearchSub;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldDZTDirectory;
    private javax.swing.JTextField jTextFieldDZTOverlap;
    private javax.swing.JTextField jTextFieldDZTQuality;
    private javax.swing.JTextField jTextFieldDZTTileSize;
    private javax.swing.JTextField jTextFieldECDirectory;
    private javax.swing.JTextField jTextFieldECOverlap;
    private javax.swing.JTextField jTextFieldECQuality;
    private javax.swing.JTextField jTextFieldGEDirectory;
    private javax.swing.JTextField jTextFieldGESearchDepth;
    private javax.swing.JTextField jTextFieldMemoryLimit;
    // End of variables declaration//GEN-END:variables
    private AggregatedSettings aggstngs;
    private boolean allowCloseFlag;
}