/*
 * SettingsWindowView.java
 *
 * Created on 2010-03-18, 01:20:03
 */
package com.panozona.converter;

import com.panozona.converter.maintable.TaskTableModel;
import com.panozona.converter.settings.AggregatedSettings;
import com.panozona.converter.utils.FileFilterDir;
import com.panozona.converter.utils.FileFilterJar;
import com.panozona.converter.utils.Messages;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.KeyStroke;

/** 
 * @author Marek Standio
 */
public class SettingsWindowView extends javax.swing.JFrame {

    private TaskTableModel taskTableModel;
    private AggregatedSettings aggstngs;
    private String initialmemoryLimitValue = "-1";
    private boolean allowCloseFlag;

    /** Creates new form SettingsWindowView */
    public SettingsWindowView(TaskTableModel taskTableModel) {
        initComponents();
        setTitle("SaladoConverter settings");
        //setIconImage(Toolkit.getDefaultToolkit().getImage(MainWindowView.class.getResource("resources/icons/appicon.png")));
        this.taskTableModel = taskTableModel;
        aggstngs = AggregatedSettings.getInstance();
        allowCloseFlag = true;

        jTabbedPaneequirectangualrFiller.remove(DeepZoomTilerTab);
        TabbedPane.remove(AutosizeTab);
        TabbedPane.remove(ComponentsTab);
        jCheckBoxGERemoveObsoleteDZ.setVisible(false);
        jCheckBoxGEOverwriteOutput.setVisible(false);

        ActionListener actionListenerESC = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onClose();
            }
        };

        KeyStroke strokeESC = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        this.getRootPane().registerKeyboardAction(actionListenerESC, strokeESC, JComponent.WHEN_IN_FOCUSED_WINDOW);

        ActionListener actionListenerENTER = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                jButtonOKActionPerformed(null);
            }
        };

        KeyStroke strokeENTER = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        this.getRootPane().registerKeyboardAction(actionListenerENTER, strokeENTER, JComponent.WHEN_IN_FOCUSED_WINDOW);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        TabbedPane = new javax.swing.JTabbedPane();
        GeneralTab = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonGERestoreDefault = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldGEDirectory = new javax.swing.JTextField();
        jButtonGEBrowseDirectory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldGEMemoryLimit = new javax.swing.JTextField();
        jCheckBoxGERemoveObsoleteDZ = new javax.swing.JCheckBox();
        jCheckBoxGEOverwriteOutput = new javax.swing.JCheckBox();
        AutosizeTab = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonOPTRestoreDefault = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldOPTResizePercent = new javax.swing.JTextField();
        jTextFieldOPTMaxTileSize = new javax.swing.JTextField();
        jTextFieldOPTMinTileSize = new javax.swing.JTextField();
        EquirectangularToCubicTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldECOverlap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldECDirectory = new javax.swing.JTextField();
        jButtonECBrowseDirectory = new javax.swing.JButton();
        jComboBoxECInterpolation = new javax.swing.JComboBox();
        jButtonECRestoreDefault = new javax.swing.JButton();
        ZoomifyTilerTab = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldZYTQuality = new javax.swing.JTextField();
        jTextFieldZYTTileSize = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldZYTDirectory = new javax.swing.JTextField();
        jButtonZYTBrowseDirectory = new javax.swing.JButton();
        jButtonZYTRestoreDefault = new javax.swing.JButton();
        ResizerTab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonRESRestoreDefault = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldRESDirectory = new javax.swing.JTextField();
        jButtonRESBrowseDirectory = new javax.swing.JButton();
        SkyboxMakerTab = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldSBMQuality = new javax.swing.JTextField();
        jTextFieldSBMPreviewSize = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldSBMDirectory = new javax.swing.JTextField();
        jButtonSBMBrowseDirectory = new javax.swing.JButton();
        jButtonSBMRestoreDefault = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButtonERFBrowseDirectory = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldERFDirectory = new javax.swing.JTextField();
        jButtonERFRestoreDefault = new javax.swing.JButton();
        ComponentsTab = new javax.swing.JPanel();
        jTabbedPaneequirectangualrFiller = new javax.swing.JTabbedPane();
        DeepZoomTilerTab = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDZTQuality = new javax.swing.JTextField();
        jTextFieldDZTTileOverlap = new javax.swing.JTextField();
        jTextFieldDZTTileSize = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDZTDirectory = new javax.swing.JTextField();
        jButtonDZTBrowseDirectory = new javax.swing.JButton();
        jButtonDZTRestoreDefault = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser.setName("jFileChooser"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        setResizable(false);

        TabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.panozona.converter.SaladoConverter.class).getContext().getResourceMap(SettingsWindowView.class);
        TabbedPane.setToolTipText(resourceMap.getString("TabbedPane.toolTipText")); // NOI18N
        TabbedPane.setName("TabbedPane"); // NOI18N

        GeneralTab.setName("GeneralTab"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jButtonGERestoreDefault.setText(resourceMap.getString("jButtonGERestoreDefault.text")); // NOI18N
        jButtonGERestoreDefault.setActionCommand(resourceMap.getString("jButtonGERestoreDefault.actionCommand")); // NOI18N
        jButtonGERestoreDefault.setName("jButtonGERestoreDefault"); // NOI18N
        jButtonGERestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGERestoreDefaultActionPerformed(evt);
            }
        });

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jTextFieldGEDirectory.setName("jTextFieldGEDirectory"); // NOI18N

        jButtonGEBrowseDirectory.setText(resourceMap.getString("jButtonGEBrowseDirectory.text")); // NOI18N
        jButtonGEBrowseDirectory.setName("jButtonGEBrowseDirectory"); // NOI18N
        jButtonGEBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGEBrowseDirectoryActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextFieldGEMemoryLimit.setText(resourceMap.getString("jTextFieldGEMemoryLimit.text")); // NOI18N
        jTextFieldGEMemoryLimit.setName("jTextFieldGEMemoryLimit"); // NOI18N

        jCheckBoxGERemoveObsoleteDZ.setText(resourceMap.getString("jCheckBoxGERemoveObsoleteDZ.text")); // NOI18N
        jCheckBoxGERemoveObsoleteDZ.setName("jCheckBoxGERemoveObsoleteDZ"); // NOI18N

        jCheckBoxGEOverwriteOutput.setText(resourceMap.getString("jCheckBoxGEOverwriteOutput.text")); // NOI18N
        jCheckBoxGEOverwriteOutput.setName("jCheckBoxGEOverwriteOutput"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGERestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxGERemoveObsoleteDZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldGEDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGEBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldGEMemoryLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(jCheckBoxGEOverwriteOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldGEDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGEBrowseDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGEMemoryLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxGERemoveObsoleteDZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxGEOverwriteOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButtonGERestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout GeneralTabLayout = new javax.swing.GroupLayout(GeneralTab);
        GeneralTab.setLayout(GeneralTabLayout);
        GeneralTabLayout.setHorizontalGroup(
            GeneralTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GeneralTabLayout.setVerticalGroup(
            GeneralTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("GeneralTab.TabConstraints.tabTitle"), GeneralTab); // NOI18N

        AutosizeTab.setName("AutosizeTab"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        jButtonOPTRestoreDefault.setText(resourceMap.getString("jButtonOPTRestoreDefault.text")); // NOI18N
        jButtonOPTRestoreDefault.setName("jButtonOPTRestoreDefault"); // NOI18N
        jButtonOPTRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOPTRestoreDefaultActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jTextFieldOPTResizePercent.setText(resourceMap.getString("jTextFieldOPTResizePercent.text")); // NOI18N
        jTextFieldOPTResizePercent.setName("jTextFieldOPTResizePercent"); // NOI18N

        jTextFieldOPTMaxTileSize.setText(resourceMap.getString("jTextFieldOPTMaxTileSize.text")); // NOI18N
        jTextFieldOPTMaxTileSize.setName("jTextFieldOPTMaxTileSize"); // NOI18N

        jTextFieldOPTMinTileSize.setText(resourceMap.getString("jTextFieldOPTMinTileSize.text")); // NOI18N
        jTextFieldOPTMinTileSize.setName("jTextFieldOPTMinTileSize"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOPTRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldOPTMinTileSize)
                            .addComponent(jTextFieldOPTMaxTileSize)
                            .addComponent(jTextFieldOPTResizePercent, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldOPTResizePercent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldOPTMaxTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldOPTMinTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jButtonOPTRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout AutosizeTabLayout = new javax.swing.GroupLayout(AutosizeTab);
        AutosizeTab.setLayout(AutosizeTabLayout);
        AutosizeTabLayout.setHorizontalGroup(
            AutosizeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutosizeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AutosizeTabLayout.setVerticalGroup(
            AutosizeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutosizeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("AutosizeTab.TabConstraints.tabTitle"), AutosizeTab); // NOI18N

        EquirectangularToCubicTab.setName("EquirectangularToCubicTab"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldECOverlap.setText(resourceMap.getString("jTextFieldECOverlap.text")); // NOI18N
        jTextFieldECOverlap.setName("jTextFieldECOverlap"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jTextFieldECDirectory.setText(resourceMap.getString("jTextFieldECDirectory.text")); // NOI18N
        jTextFieldECDirectory.setName("jTextFieldECDirectory"); // NOI18N

        jButtonECBrowseDirectory.setText(resourceMap.getString("jButtonECBrowseDirectory.text")); // NOI18N
        jButtonECBrowseDirectory.setName("jButtonECBrowseDirectory"); // NOI18N
        jButtonECBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonECBrowseDirectoryActionPerformed(evt);
            }
        });

        jComboBoxECInterpolation.setName("jComboBoxECInterpolation"); // NOI18N

        jButtonECRestoreDefault.setText(resourceMap.getString("jButtonECRestoreDefault.text")); // NOI18N
        jButtonECRestoreDefault.setName("jButtonECRestoreDefault"); // NOI18N
        jButtonECRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonECRestoreDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonECRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldECDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonECBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldECOverlap, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(jComboBoxECInterpolation, 0, 333, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldECOverlap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxECInterpolation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldECDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonECBrowseDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jButtonECRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout EquirectangularToCubicTabLayout = new javax.swing.GroupLayout(EquirectangularToCubicTab);
        EquirectangularToCubicTab.setLayout(EquirectangularToCubicTabLayout);
        EquirectangularToCubicTabLayout.setHorizontalGroup(
            EquirectangularToCubicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquirectangularToCubicTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EquirectangularToCubicTabLayout.setVerticalGroup(
            EquirectangularToCubicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquirectangularToCubicTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("EquirectangularToCubicTab.TabConstraints.tabTitle"), EquirectangularToCubicTab); // NOI18N

        ZoomifyTilerTab.setName("ZoomifyTilerTab"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jTextFieldZYTQuality.setName("jTextFieldZYTQuality"); // NOI18N

        jTextFieldZYTTileSize.setName("jTextFieldZYTTileSize"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jTextFieldZYTDirectory.setName("jTextFieldZYTDirectory"); // NOI18N

        jButtonZYTBrowseDirectory.setText(resourceMap.getString("jButtonZYTBrowseDirectory.text")); // NOI18N
        jButtonZYTBrowseDirectory.setName("jButtonZYTBrowseDirectory"); // NOI18N
        jButtonZYTBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZYTBrowseDirectoryActionPerformed(evt);
            }
        });

        jButtonZYTRestoreDefault.setText(resourceMap.getString("jButtonZYTRestoreDefault.text")); // NOI18N
        jButtonZYTRestoreDefault.setName("jButtonZYTRestoreDefault"); // NOI18N
        jButtonZYTRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZYTRestoreDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextFieldZYTDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonZYTBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldZYTQuality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jTextFieldZYTTileSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addComponent(jButtonZYTRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldZYTTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZYTQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZYTDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZYTBrowseDirectory)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButtonZYTRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout ZoomifyTilerTabLayout = new javax.swing.GroupLayout(ZoomifyTilerTab);
        ZoomifyTilerTab.setLayout(ZoomifyTilerTabLayout);
        ZoomifyTilerTabLayout.setHorizontalGroup(
            ZoomifyTilerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZoomifyTilerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ZoomifyTilerTabLayout.setVerticalGroup(
            ZoomifyTilerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZoomifyTilerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("ZoomifyTilerTab.TabConstraints.tabTitle"), ZoomifyTilerTab); // NOI18N

        ResizerTab.setName("ResizerTab"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        jButtonRESRestoreDefault.setText(resourceMap.getString("jButtonRESRestoreDefault.text")); // NOI18N
        jButtonRESRestoreDefault.setName("jButtonRESRestoreDefault"); // NOI18N
        jButtonRESRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRESRestoreDefaultActionPerformed(evt);
            }
        });

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jTextFieldRESDirectory.setName("jTextFieldRESDirectory"); // NOI18N

        jButtonRESBrowseDirectory.setText(resourceMap.getString("jButtonRESBrowseDirectory.text")); // NOI18N
        jButtonRESBrowseDirectory.setName("jButtonRESBrowseDirectory"); // NOI18N
        jButtonRESBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRESBrowseDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRESRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldRESDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRESBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldRESDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRESBrowseDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jButtonRESRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout ResizerTabLayout = new javax.swing.GroupLayout(ResizerTab);
        ResizerTab.setLayout(ResizerTabLayout);
        ResizerTabLayout.setHorizontalGroup(
            ResizerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResizerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ResizerTabLayout.setVerticalGroup(
            ResizerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResizerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("ResizerTab.TabConstraints.tabTitle"), ResizerTab); // NOI18N

        SkyboxMakerTab.setName("SkyboxMakerTab"); // NOI18N

        jPanel7.setName("jPanel7"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jTextFieldSBMQuality.setName("jTextFieldSBMQuality"); // NOI18N

        jTextFieldSBMPreviewSize.setName("jTextFieldSBMPreviewSize"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jTextFieldSBMDirectory.setName("jTextFieldSBMDirectory"); // NOI18N

        jButtonSBMBrowseDirectory.setText(resourceMap.getString("jButtonSBMBrowseDirectory.text")); // NOI18N
        jButtonSBMBrowseDirectory.setName("jButtonSBMBrowseDirectory"); // NOI18N
        jButtonSBMBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSBMBrowseDirectoryActionPerformed(evt);
            }
        });

        jButtonSBMRestoreDefault.setText(resourceMap.getString("jButtonSBMRestoreDefault.text")); // NOI18N
        jButtonSBMRestoreDefault.setName("jButtonSBMRestoreDefault"); // NOI18N
        jButtonSBMRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSBMRestoreDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jTextFieldSBMDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSBMBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldSBMQuality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jTextFieldSBMPreviewSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addComponent(jButtonSBMRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldSBMPreviewSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSBMQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSBMDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSBMBrowseDirectory)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButtonSBMRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout SkyboxMakerTabLayout = new javax.swing.GroupLayout(SkyboxMakerTab);
        SkyboxMakerTab.setLayout(SkyboxMakerTabLayout);
        SkyboxMakerTabLayout.setHorizontalGroup(
            SkyboxMakerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkyboxMakerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SkyboxMakerTabLayout.setVerticalGroup(
            SkyboxMakerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkyboxMakerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("SkyboxMakerTab.TabConstraints.tabTitle"), SkyboxMakerTab); // NOI18N

        jPanel8.setName("jPanel8"); // NOI18N

        jPanel9.setName("jPanel9"); // NOI18N

        jButtonERFBrowseDirectory.setText(resourceMap.getString("jButtonERFBrowseDirectory.text")); // NOI18N
        jButtonERFBrowseDirectory.setName("jButtonERFBrowseDirectory"); // NOI18N
        jButtonERFBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonERFBrowseDirectoryActionPerformed(evt);
            }
        });

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jTextFieldERFDirectory.setName("jTextFieldERFDirectory"); // NOI18N

        jButtonERFRestoreDefault.setText(resourceMap.getString("jButtonERFRestoreDefault.text")); // NOI18N
        jButtonERFRestoreDefault.setName("jButtonERFRestoreDefault"); // NOI18N
        jButtonERFRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonERFRestoreDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonERFRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldERFDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonERFBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldERFDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonERFBrowseDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jButtonERFRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab(resourceMap.getString("jPanel8.TabConstraints.tabTitle"), jPanel8); // NOI18N

        ComponentsTab.setName("ComponentsTab"); // NOI18N

        jTabbedPaneequirectangualrFiller.setAutoscrolls(true);
        jTabbedPaneequirectangualrFiller.setName("jTabbedPaneequirectangualrFiller"); // NOI18N

        DeepZoomTilerTab.setName("DeepZoomTilerTab"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jTextFieldDZTQuality.setName("jTextFieldDZTQuality"); // NOI18N

        jTextFieldDZTTileOverlap.setName("jTextFieldDZTTileOverlap"); // NOI18N

        jTextFieldDZTTileSize.setName("jTextFieldDZTTileSize"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jTextFieldDZTDirectory.setText(resourceMap.getString("jTextFieldDZTDirectory.text")); // NOI18N
        jTextFieldDZTDirectory.setName("jTextFieldDZTDirectory"); // NOI18N

        jButtonDZTBrowseDirectory.setText(resourceMap.getString("jButtonDZTBrowseDirectory.text")); // NOI18N
        jButtonDZTBrowseDirectory.setName("jButtonDZTBrowseDirectory"); // NOI18N
        jButtonDZTBrowseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDZTBrowseDirectoryActionPerformed(evt);
            }
        });

        jButtonDZTRestoreDefault.setText(resourceMap.getString("jButtonDZTRestoreDefault.text")); // NOI18N
        jButtonDZTRestoreDefault.setName("jButtonDZTRestoreDefault"); // NOI18N
        jButtonDZTRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDZTRestoreDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDZTRestoreDefault, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldDZTDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDZTBrowseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldDZTTileOverlap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jTextFieldDZTQuality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jTextFieldDZTTileSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDZTTileOverlap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDZTTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDZTQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDZTDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDZTBrowseDirectory)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButtonDZTRestoreDefault)
                .addContainerGap())
        );

        javax.swing.GroupLayout DeepZoomTilerTabLayout = new javax.swing.GroupLayout(DeepZoomTilerTab);
        DeepZoomTilerTab.setLayout(DeepZoomTilerTabLayout);
        DeepZoomTilerTabLayout.setHorizontalGroup(
            DeepZoomTilerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeepZoomTilerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DeepZoomTilerTabLayout.setVerticalGroup(
            DeepZoomTilerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeepZoomTilerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneequirectangualrFiller.addTab(resourceMap.getString("DeepZoomTilerTab.TabConstraints.tabTitle"), DeepZoomTilerTab); // NOI18N

        javax.swing.GroupLayout ComponentsTabLayout = new javax.swing.GroupLayout(ComponentsTab);
        ComponentsTab.setLayout(ComponentsTabLayout);
        ComponentsTabLayout.setHorizontalGroup(
            ComponentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneequirectangualrFiller, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        ComponentsTabLayout.setVerticalGroup(
            ComponentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneequirectangualrFiller, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        jTabbedPaneequirectangualrFiller.getAccessibleContext().setAccessibleName(resourceMap.getString("jTabbedPane1.AccessibleContext.accessibleName")); // NOI18N

        TabbedPane.addTab(resourceMap.getString("ComponentsTab.TabConstraints.tabTitle"), ComponentsTab); // NOI18N

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOK.setText(resourceMap.getString("jButtonOK.text")); // NOI18N
        jButtonOK.setName("jButtonOK"); // NOI18N
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addComponent(TabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addContainerGap())
        );

        TabbedPane.getAccessibleContext().setAccessibleName(resourceMap.getString("TabbedPane.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        collectAllData();
        if (allowCloseFlag) {
            if (!initialmemoryLimitValue.equals(jTextFieldGEMemoryLimit.getText())) {
                JOptionPane.showMessageDialog(this, Messages.GE_MEMORY_LIMIT_WARNING);
            }
            Controller.getInstance().applyCommand();
            onClose();
        }
        allowCloseFlag = true;
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        onClose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonGERestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGERestoreDefaultActionPerformed
        jTextFieldGEDirectory.setText(aggstngs.ge.getDefaultTmpDir());
        jTextFieldGEMemoryLimit.setText(Integer.toString(aggstngs.ge.getDefaultMemoryLimit()));
        jCheckBoxGERemoveObsoleteDZ.setSelected(aggstngs.ge.getDefaultRemoveObsolete());
        jCheckBoxGEOverwriteOutput.setSelected(aggstngs.ge.getDefaultOverwriteOutput());
    }//GEN-LAST:event_jButtonGERestoreDefaultActionPerformed

    private void jButtonGEBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGEBrowseDirectoryActionPerformed
        jFileChooser.resetChoosableFileFilters();
        jFileChooser.setSelectedFile(new File(""));
        jFileChooser.setFileFilter(new FileFilterDir());
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.setDialogTitle("Browse for tmp directory");
        jFileChooser.setCurrentDirectory(new File(aggstngs.ge.getTmpDir()));
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jTextFieldGEDirectory.setText(jFileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonGEBrowseDirectoryActionPerformed

    private void jButtonOPTRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOPTRestoreDefaultActionPerformed
        jTextFieldOPTResizePercent.setText(Integer.toString(aggstngs.opt.getDefaultResizePercent()));
        jTextFieldOPTMaxTileSize.setText(Integer.toString(aggstngs.opt.getDefaultMaxTileSize()));
        jTextFieldOPTMinTileSize.setText(Integer.toString(aggstngs.opt.getDefaultMinTileSize()));
    }//GEN-LAST:event_jButtonOPTRestoreDefaultActionPerformed

private void jButtonSBMRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSBMRestoreDefaultActionPerformed
    jTextFieldSBMPreviewSize.setText(Integer.toString(aggstngs.sbm.getDefaultPreviewSize()));
    jTextFieldSBMQuality.setText(Float.toString(aggstngs.sbm.getDefaultQuality()));
    jTextFieldSBMDirectory.setText(aggstngs.sbm.getDefaultJarDir());
}//GEN-LAST:event_jButtonSBMRestoreDefaultActionPerformed

private void jButtonSBMBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSBMBrowseDirectoryActionPerformed
    jFileChooser.resetChoosableFileFilters();
    jFileChooser.setSelectedFile(new File(""));
    jFileChooser.setFileFilter(new FileFilterJar());
    jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    jFileChooser.setDialogTitle("Browse for SkyboxMaker.jar");
    jFileChooser.setCurrentDirectory(new File(aggstngs.sbm.getJarDir()));
    int returnVal = jFileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        jTextFieldSBMDirectory.setText(jFileChooser.getSelectedFile().getAbsolutePath());
    }
}//GEN-LAST:event_jButtonSBMBrowseDirectoryActionPerformed

private void jButtonRESBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESBrowseDirectoryActionPerformed
    jFileChooser.resetChoosableFileFilters();
    jFileChooser.setSelectedFile(new File(""));
    jFileChooser.setFileFilter(new FileFilterJar());
    jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    jFileChooser.setDialogTitle("Browse for Resizer.jar");
    jFileChooser.setCurrentDirectory(new File(aggstngs.res.getJarDir()));
    int returnVal = jFileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        jTextFieldRESDirectory.setText(jFileChooser.getSelectedFile().getAbsolutePath());
    }
}//GEN-LAST:event_jButtonRESBrowseDirectoryActionPerformed

private void jButtonRESRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESRestoreDefaultActionPerformed
    jTextFieldRESDirectory.setText(aggstngs.res.getDefaultJarDir());
}//GEN-LAST:event_jButtonRESRestoreDefaultActionPerformed

private void jButtonZYTRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZYTRestoreDefaultActionPerformed
    jTextFieldZYTTileSize.setText(Integer.toString(aggstngs.zyt.getDefaultTileSize()));
    jTextFieldZYTQuality.setText(Float.toString(aggstngs.zyt.getDefaultQuality()));
    jTextFieldZYTDirectory.setText(aggstngs.zyt.getDefaultJarDir());
}//GEN-LAST:event_jButtonZYTRestoreDefaultActionPerformed

private void jButtonZYTBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZYTBrowseDirectoryActionPerformed
    jFileChooser.resetChoosableFileFilters();
    jFileChooser.setSelectedFile(new File(""));
    jFileChooser.setFileFilter(new FileFilterJar());
    jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    jFileChooser.setDialogTitle("Browse for ZoomifyTiler.jar");
    jFileChooser.setCurrentDirectory(new File(aggstngs.zyt.getJarDir()));
    int returnVal = jFileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        jTextFieldZYTDirectory.setText(jFileChooser.getSelectedFile().getAbsolutePath());
    }
}//GEN-LAST:event_jButtonZYTBrowseDirectoryActionPerformed

private void jButtonDZTRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDZTRestoreDefaultActionPerformed
    jTextFieldDZTTileOverlap.setText(Integer.toString(aggstngs.dzt.getDefaultTileOverlap()));
    jTextFieldDZTTileSize.setText(Integer.toString(aggstngs.dzt.getDefaultTileSize()));
    jTextFieldDZTQuality.setText(Float.toString(aggstngs.dzt.getDefaultQuality()));
    jTextFieldDZTDirectory.setText(aggstngs.dzt.getDefaultJarDir());
}//GEN-LAST:event_jButtonDZTRestoreDefaultActionPerformed

private void jButtonDZTBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDZTBrowseDirectoryActionPerformed
    jFileChooser.resetChoosableFileFilters();
    jFileChooser.setSelectedFile(new File(""));
    jFileChooser.setFileFilter(new FileFilterJar());
    jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    jFileChooser.setDialogTitle("Browse for DeepZoomTiler.jar");
    jFileChooser.setCurrentDirectory(new File(aggstngs.dzt.getJarDir()));
    int returnVal = jFileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        jTextFieldDZTDirectory.setText(jFileChooser.getSelectedFile().getAbsolutePath());
    }
}//GEN-LAST:event_jButtonDZTBrowseDirectoryActionPerformed

private void jButtonECRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonECRestoreDefaultActionPerformed
    jTextFieldECOverlap.setText(Integer.toString(aggstngs.ec.getDefaultWallOverlap()));
    jComboBoxECInterpolation.setSelectedItem(aggstngs.ec.getDefaultInterpolation());
    jTextFieldECDirectory.setText(aggstngs.ec.getDefaultJarDir());
}//GEN-LAST:event_jButtonECRestoreDefaultActionPerformed

private void jButtonECBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonECBrowseDirectoryActionPerformed
    jFileChooser.resetChoosableFileFilters();
    jFileChooser.setSelectedFile(new File(""));
    jFileChooser.setFileFilter(new FileFilterJar());
    jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    jFileChooser.setDialogTitle("Browse for EquirectangularToCubic.jar");
    jFileChooser.setCurrentDirectory(new File(aggstngs.ec.getJarDir()));
    int returnVal = jFileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        jTextFieldECDirectory.setText(jFileChooser.getSelectedFile().getAbsolutePath());
    }
}//GEN-LAST:event_jButtonECBrowseDirectoryActionPerformed

private void jButtonERFBrowseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonERFBrowseDirectoryActionPerformed
    jFileChooser.resetChoosableFileFilters();
    jFileChooser.setSelectedFile(new File(""));
    jFileChooser.setFileFilter(new FileFilterJar());
    jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    jFileChooser.setDialogTitle("Browse for EquirectangularFiller.jar");
    jFileChooser.setCurrentDirectory(new File(aggstngs.erf.getJarDir()));
    int returnVal = jFileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        jTextFieldERFDirectory.setText(jFileChooser.getSelectedFile().getAbsolutePath());
    }
}//GEN-LAST:event_jButtonERFBrowseDirectoryActionPerformed

private void jButtonERFRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonERFRestoreDefaultActionPerformed
    jTextFieldERFDirectory.setText(aggstngs.erf.getDefaultJarDir());
}//GEN-LAST:event_jButtonERFRestoreDefaultActionPerformed

    public void displayAggregatedSettings() {

        jComboBoxECInterpolation.setModel(new DefaultComboBoxModel(this.aggstngs.ec.getInterpolationNames()));

        jTextFieldGEDirectory.setText(aggstngs.ge.getTmpDir());
        jTextFieldGEMemoryLimit.setText(Integer.toString(aggstngs.ge.getMemoryLimit()));
        initialmemoryLimitValue = Integer.toString(aggstngs.ge.getMemoryLimit());
        jCheckBoxGERemoveObsoleteDZ.setSelected(aggstngs.ge.getRemoveObsolete());
        jCheckBoxGEOverwriteOutput.setSelected(aggstngs.ge.getOverwriteOutput());

        jTextFieldOPTResizePercent.setText(Integer.toString(aggstngs.opt.getResizePercent()));
        jTextFieldOPTMaxTileSize.setText(Integer.toString(aggstngs.opt.getMaxTileSize()));
        jTextFieldOPTMinTileSize.setText(Integer.toString(aggstngs.opt.getMinTileSize()));

        jTextFieldZYTTileSize.setText(Integer.toString(aggstngs.zyt.getTileSize()));
        jTextFieldZYTQuality.setText(Float.toString(aggstngs.zyt.getQuality()));
        jTextFieldZYTDirectory.setText(aggstngs.zyt.getJarDir());

        jTextFieldDZTTileOverlap.setText(Integer.toString(aggstngs.dzt.getTileOverlap()));
        jTextFieldDZTTileSize.setText(Integer.toString(aggstngs.dzt.getTileSize()));
        jTextFieldDZTQuality.setText(Float.toString(aggstngs.dzt.getQuality()));
        jTextFieldDZTDirectory.setText(aggstngs.dzt.getJarDir());

        jTextFieldSBMPreviewSize.setText(Integer.toString(aggstngs.sbm.getPreviewSize()));
        jTextFieldSBMQuality.setText(Float.toString(aggstngs.sbm.getQuality()));
        jTextFieldSBMDirectory.setText(aggstngs.sbm.getJarDir());

        jTextFieldECOverlap.setText(Integer.toString(aggstngs.ec.getWallOverlap()));
        jComboBoxECInterpolation.setSelectedItem(aggstngs.ec.getInterpolation());
        jTextFieldECDirectory.setText(aggstngs.ec.getJarDir());

        jTextFieldRESDirectory.setText(aggstngs.res.getJarDir());

        jTextFieldERFDirectory.setText(aggstngs.erf.getJarDir());
    }

    private void collectAllData() {
        try {
            aggstngs.ge.setTmpDir(jTextFieldGEDirectory.getText());
            aggstngs.ge.setMemoryLimit(jTextFieldGEMemoryLimit.getText());
            aggstngs.ge.setRemoveObsolete(jCheckBoxGERemoveObsoleteDZ.isSelected());
            aggstngs.ge.setOverwriteOutput(jCheckBoxGEOverwriteOutput.isSelected());

            aggstngs.opt.setResizePercent(jTextFieldOPTResizePercent.getText());
            aggstngs.opt.setMaxTileSize(jTextFieldOPTMaxTileSize.getText());
            aggstngs.opt.setMinTileSize(jTextFieldOPTMinTileSize.getText());

            aggstngs.dzt.setTileOverlap(jTextFieldDZTTileOverlap.getText());
            aggstngs.dzt.setTileSize(jTextFieldDZTTileSize.getText());
            aggstngs.dzt.setQuality(jTextFieldDZTQuality.getText());
            aggstngs.dzt.setJarDir(jTextFieldDZTDirectory.getText());

            aggstngs.sbm.setPreviewSize(jTextFieldSBMPreviewSize.getText());
            aggstngs.sbm.setQuality(jTextFieldSBMQuality.getText());
            aggstngs.sbm.setJarDir(jTextFieldSBMDirectory.getText());

            aggstngs.ec.setWallOverlap(jTextFieldECOverlap.getText());
            aggstngs.ec.setInterpolation(jComboBoxECInterpolation.getSelectedItem().toString());
            aggstngs.ec.setJarDir(jTextFieldECDirectory.getText());

            aggstngs.res.setJarDir(jTextFieldRESDirectory.getText());

            aggstngs.erf.setJarDir(jTextFieldERFDirectory.getText());


        } catch (IllegalArgumentException ex) {
            showOptionPane(ex.getMessage());
        }
    }

    private void showOptionPane(String message) {
        JOptionPane.showMessageDialog(this, message);
        allowCloseFlag = false;
    }

    private void onClose() {
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AutosizeTab;
    private javax.swing.JPanel ComponentsTab;
    private javax.swing.JPanel DeepZoomTilerTab;
    private javax.swing.JPanel EquirectangularToCubicTab;
    private javax.swing.JPanel GeneralTab;
    private javax.swing.JPanel ResizerTab;
    private javax.swing.JPanel SkyboxMakerTab;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JPanel ZoomifyTilerTab;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDZTBrowseDirectory;
    private javax.swing.JButton jButtonDZTRestoreDefault;
    private javax.swing.JButton jButtonECBrowseDirectory;
    private javax.swing.JButton jButtonECRestoreDefault;
    private javax.swing.JButton jButtonERFBrowseDirectory;
    private javax.swing.JButton jButtonERFRestoreDefault;
    private javax.swing.JButton jButtonGEBrowseDirectory;
    private javax.swing.JButton jButtonGERestoreDefault;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonOPTRestoreDefault;
    private javax.swing.JButton jButtonRESBrowseDirectory;
    private javax.swing.JButton jButtonRESRestoreDefault;
    private javax.swing.JButton jButtonSBMBrowseDirectory;
    private javax.swing.JButton jButtonSBMRestoreDefault;
    private javax.swing.JButton jButtonZYTBrowseDirectory;
    private javax.swing.JButton jButtonZYTRestoreDefault;
    private javax.swing.JCheckBox jCheckBoxGEOverwriteOutput;
    private javax.swing.JCheckBox jCheckBoxGERemoveObsoleteDZ;
    private javax.swing.JComboBox jComboBoxECInterpolation;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPaneequirectangualrFiller;
    private javax.swing.JTextField jTextFieldDZTDirectory;
    private javax.swing.JTextField jTextFieldDZTQuality;
    private javax.swing.JTextField jTextFieldDZTTileOverlap;
    private javax.swing.JTextField jTextFieldDZTTileSize;
    private javax.swing.JTextField jTextFieldECDirectory;
    private javax.swing.JTextField jTextFieldECOverlap;
    private javax.swing.JTextField jTextFieldERFDirectory;
    private javax.swing.JTextField jTextFieldGEDirectory;
    private javax.swing.JTextField jTextFieldGEMemoryLimit;
    private javax.swing.JTextField jTextFieldOPTMaxTileSize;
    private javax.swing.JTextField jTextFieldOPTMinTileSize;
    private javax.swing.JTextField jTextFieldOPTResizePercent;
    private javax.swing.JTextField jTextFieldRESDirectory;
    private javax.swing.JTextField jTextFieldSBMDirectory;
    private javax.swing.JTextField jTextFieldSBMPreviewSize;
    private javax.swing.JTextField jTextFieldSBMQuality;
    private javax.swing.JTextField jTextFieldZYTDirectory;
    private javax.swing.JTextField jTextFieldZYTQuality;
    private javax.swing.JTextField jTextFieldZYTTileSize;
    // End of variables declaration//GEN-END:variables
}
