/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TaskSettingsView.java
 *
 * Created on 2010-12-08, 10:06:59
 */
package com.panozona.converter;

import com.panozona.converter.maintable.TaskTableModel;
import com.panozona.converter.settings.TSKSettings;
import com.panozona.converter.utils.Info;
import com.panozona.converter.utils.InfoException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Marek
 */
public class TaskSettingsView extends javax.swing.JFrame {

    private TSKSettings taskSettings;
    private TaskTableModel taskTableModel;
    private Controller controller;

    /** Creates new form TaskSettingsView */
    public TaskSettingsView(TaskTableModel taskTableModel, Controller controller) {
        setTitle("Task settings");
        setIconImage(Toolkit.getDefaultToolkit().getImage(MainWindowView.class.getResource("resources/icons/appicon.png")));
        allowCloseFlag = true;
        this.taskTableModel = taskTableModel;
        this.controller = controller;
        initComponents();

        ActionListener actionListenerESC = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                dispose();
            }
        };

        KeyStroke strokeESC = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        this.getRootPane().registerKeyboardAction(actionListenerESC, strokeESC, JComponent.WHEN_IN_FOCUSED_WINDOW);

        ActionListener actionListenerENTER = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                jButtonTaskOKActionPerformed(null);
            }
        };

        KeyStroke strokeENTER = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        this.getRootPane().registerKeyboardAction(actionListenerENTER, strokeENTER, JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    public void displayTaskSettings(TSKSettings taskSettings) {
        this.taskSettings = taskSettings;
        jTextFieldTaskResize.setText(taskSettings.getCubeNewSize());
        jLabelOriginalValue.setText(taskSettings.getDefaultCubeNewSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTaskOK = new javax.swing.JButton();
        jButtonTaskCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTaskResize = new javax.swing.JTextField();
        jLabelOriginalValue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.panozona.converter.SaladoConverter.class).getContext().getResourceMap(TaskSettingsView.class);
        jButtonTaskOK.setText(resourceMap.getString("jButtonTaskOK.text")); // NOI18N
        jButtonTaskOK.setName("jButtonTaskOK"); // NOI18N
        jButtonTaskOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaskOKActionPerformed(evt);
            }
        });

        jButtonTaskCancel.setText(resourceMap.getString("jButtonTaskCancel.text")); // NOI18N
        jButtonTaskCancel.setName("jButtonTaskCancel"); // NOI18N
        jButtonTaskCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaskCancelActionPerformed(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextFieldTaskResize.setText(resourceMap.getString("jTextFieldTaskResize.text")); // NOI18N
        jTextFieldTaskResize.setName("jTextFieldTaskResize"); // NOI18N

        jLabelOriginalValue.setText(resourceMap.getString("jLabelOriginalValue.text")); // NOI18N
        jLabelOriginalValue.setName("jLabelOriginalValue"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOriginalValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTaskResize, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTaskResize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOriginalValue)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTaskOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTaskCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTaskCancel)
                    .addComponent(jButtonTaskOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTaskOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaskOKActionPerformed
        collectAllData();
        if (allowCloseFlag) {
            this.dispose();
            taskTableModel.fireTableDataChanged();
            controller.applyCommand();
        }
        allowCloseFlag = true;
}//GEN-LAST:event_jButtonTaskOKActionPerformed

    private void jButtonTaskCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaskCancelActionPerformed
        this.dispose();
}//GEN-LAST:event_jButtonTaskCancelActionPerformed

    private void collectAllData() {
        try {
            if (jTextFieldTaskResize.getText().isEmpty()){
                taskSettings.setCubeNewSize(taskSettings.getDefaultCubeNewSize(), Info.TSK_RESIZE_ERROR);
            }else{
                taskSettings.setCubeNewSize(jTextFieldTaskResize.getText(), Info.TSK_RESIZE_ERROR);
            }
        } catch (InfoException ex) {
            showOptionPane(ex.getMessage());
        }
    }

    private void showOptionPane(String message) {
        JOptionPane.showMessageDialog(this, message);
        allowCloseFlag = false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTaskCancel;
    private javax.swing.JButton jButtonTaskOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelOriginalValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldTaskResize;
    // End of variables declaration//GEN-END:variables
    private boolean allowCloseFlag;
}
